global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules.yml"

scrape_configs:
  # Backend pods scraping configuration
  - job_name: 'backends'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: 
          - 'backend-1:8080'
          - 'backend-2:8080'  
          - 'backend-3:8080'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__address__]
        regex: '(.+):.*'
        target_label: pod_name
        replacement: '${1}'

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Optional: Monitor Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'